"""
PDF export — Step 7 "Download" (PDF option).

Builds a clean, printable PDF: form title, the filled answer sheet image,
and a JSON appendix isn't included here (JSON is offered as a separate
download in app.py per the spec).
"""

from __future__ import annotations
import io
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


def build_filled_form_pdf(title: str, filled_sheet: Image.Image, missing_fields: list[str] | None = None) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    page_w, page_h = A4

    margin = 15 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, page_h - margin, title[:80])

    c.setFont("Helvetica", 9)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawString(margin, page_h - margin - 14, "Generated by FormSathi")
    c.setFillColorRGB(0, 0, 0)

    # Fit the answer-sheet image into the remaining page area
    img_reader = ImageReader(filled_sheet)
    iw, ih = filled_sheet.size
    max_w = page_w - 2 * margin
    max_h = page_h - 2 * margin - 40
    scale = min(max_w / iw, max_h / ih)
    draw_w, draw_h = iw * scale, ih * scale

    c.drawImage(
        img_reader,
        margin,
        page_h - margin - 30 - draw_h,
        width=draw_w,
        height=draw_h,
        preserveAspectRatio=True,
    )

    if missing_fields:
        y = page_h - margin - 40 - draw_h
        c.setFont("Helvetica-Bold", 10)
        c.setFillColorRGB(0.75, 0.1, 0.1)
        c.drawString(margin, y, f"Missing required fields: {', '.join(missing_fields)}")
        c.setFillColorRGB(0, 0, 0)

    c.showPage()
    c.save()
    return buf.getvalue()
